### ISSUE TITLE
Any SolrException causes SolrStage to crash and not start again

### ISSUE THREAD

**Issue by ebbesson** [Findwise/Hydra#161]
The hydra log
2013-02-12 12:28:58,885 [Thread-9] ERROR com.findwise.hydra.StageRunner - Stage group solr-out terminated unexpectedly with exit value 1
2013-02-12 12:28:58,885 [Thread-9] INFO com.findwise.hydra.StageRunner - Starting stage group solr-out. Times started so far: 1
2013-02-12 12:28:58,886 [Thread-9] INFO com.findwise.hydra.StageRunner - Launching with command java -cp D:\Code\hydra\pipeline\solr-out*:D:\Code\hydra\pipeline\solr-out* -jar D:\Code\hydra\pipeline\solr-out\solr-out-stage.jar solr-out localhost 12001 false
2013-02-12 12:28:59,498 [Thread-26] INFO solr-out - Started 1 instances of stage: solr-out. Running with the query: {"equals":{},"touched":{"fix-broken-dates":true},"exists":{},"notEquals":{}}

Exception thrown in console
:
Exception in thread "Thread-9" java.lang.IllegalArgumentException: Hook previous
ly registered
        at java.lang.ApplicationShutdownHooks.add(Unknown Source)
        at java.lang.Runtime.addShutdownHook(Unknown Source)
        at com.findwise.hydra.StageRunner$StageDestroyer.add(StageRunner.java:29
3)
        at com.findwise.hydra.StageRunner.runGroup(StageRunner.java:207)
        at com.findwise.hydra.StageRunner.run(StageRunner.java:133)

The log states that is has been started, but when in fact is has not

**Comment by jwestberg** [comment]
Not specific to SolrOutputStage. I ran across this a few days ago too and fixed it in a bigger branch. I'll cherry-pick and push the fix later today.

Not sure when this got broken, it's been working before.

**Comment by jwestberg** [comment]
Have not looked at SolrOutput actually crashing, but the restarting issue is fixed in #164

**Comment by laserval** [comment]
Fixed by #164, closing.
