### ISSUE TITLE
Updating stage configurations sometimes causes a series of failed restarts

### ISSUE THREAD

**Issue by laserval** [Findwise/Hydra#227]
When reloading the stages, the Core attempts to clear the temporary `pipeline` for each stage and recreate the jar.

On Windows, there appear to be some file locking issues that cause the removal to fail, crashing the starting stage.

There also seems to be some race conditions for individual stages, where they cannot find their own jars.

Logs look like this:

```
2013-07-05 14:10:37 : ERROR  : Thread-46 : com.findwise.hydra.StageRunner : Stage group systest-content terminated unexpectedly with exit value 1
2013-07-05 14:10:37 : ERROR  : Thread-46 : com.findwise.hydra.StageRunner : Stage group systest-content has failed and cannot be restarted. 
2013-07-05 14:10:38 : INFO   : Thread-377 : com.findwise.hydra.StreamLogger : Received message from stage dev-strip-html (stderr): Unable to access jarfile F:\hydra\pipeline\dev-strip-html\hydra-strip-html-stage-jar-with-dependencies.jar
2013-07-05 14:10:38 : INFO   : Thread-373 : com.findwise.hydra.StreamLogger : Received message from stage wikiacc-strip-html (stderr): Exception in thread "main" 
2013-07-05 14:10:38 : INFO   : Thread-379 : com.findwise.hydra.StreamLogger : Received message from stage dev-active-directory (stderr): Unable to access jarfile F:\hydra\pipeline\dev-active-directory\hydra-active-directory-stages-jar-with-dependencies.jar
2013-07-05 14:10:38 : INFO   : Thread-375 : com.findwise.hydra.StreamLogger : Received message from stage dev-fix-absolute-link (stderr): java.io.FileNotFoundException: F:\hydra\pipeline\dev-fix-absolute-link\hydra-book-stages-jar-with-dependencies.jar (The system cannot find the path specified)
2013-07-05 14:10:38 : INFO   : Thread-375 : com.findwise.hydra.StreamLogger : Received message from stage dev-fix-absolute-link (stderr):     at java.util.zip.ZipFile.open(Native Method)
2013-07-05 14:10:38 : INFO   : Thread-375 : com.findwise.hydra.StreamLogger : Received message from stage dev-fix-absolute-link (stderr):     at java.util.zip.ZipFile.<init>(Unknown Source)
2013-07-05 14:10:38 : INFO   : Thread-375 : com.findwise.hydra.StreamLogger : Received message from stage dev-fix-absolute-link (stderr):     at java.util.jar.JarFile.<init>(Unknown Source)
2013-07-05 14:10:38 : INFO   : Thread-375 : com.findwise.hydra.StreamLogger : Received message from stage dev-fix-absolute-link (stderr):     at java.util.jar.JarFile.<init>(Unknown Source)
2013-07-05 14:10:38 : INFO   : Thread-375 : com.findwise.hydra.StreamLogger : Received message from stage dev-fix-absolute-link (stderr): Exception in thread "main" 
2013-07-05 14:10:42 : ERROR  : Thread-6 : com.findwise.hydra.StageRunner : Unable to delete the directory F:\hydra\pipeline\systest-content, containing Stage Group systest-content
java.io.IOException: Unable to delete file: pipeline\systest-content\hydra-book-stages-jar-with-dependencies.jar
    at org.apache.commons.io.FileUtils.forceDelete(FileUtils.java:1643) ~[hydra-core.jar:na]
    at org.apache.commons.io.FileUtils.cleanDirectory(FileUtils.java:1268) ~[hydra-core.jar:na]
    at org.apache.commons.io.FileUtils.deleteDirectory(FileUtils.java:1200) ~[hydra-core.jar:na]
    at com.findwise.hydra.StageRunner.removeFiles(StageRunner.java:252) [hydra-core.jar:na]
    at com.findwise.hydra.StageRunner.destroy(StageRunner.java:242) [hydra-core.jar:na]
    at com.findwise.hydra.NodeMaster.stopGroup(NodeMaster.java:116) [hydra-core.jar:na]
    at com.findwise.hydra.NodeMaster.updatePipeline(NodeMaster.java:95) [hydra-core.jar:na]
    at com.findwise.hydra.NodeMaster.run(NodeMaster.java:59) [hydra-core.jar:na]
```

**Comment by Nycander** [comment]
I hightly suspect [StageRunner:83](https://github.com/Findwise/Hydra/blob/master/core/src/main/java/com/findwise/hydra/StageRunner.java#L83)

``` java
        for(DatabaseFile df : stageGroup.getDatabaseFiles()) {
            File f = new File(targetDirectory, df.getFilename());
            files.add(f);
            IOUtils.copy(df.getInputStream(), new FileOutputStream(f)); // <-- Unclosed resource!
        }
```

I don't have time to test this on windows today though.
